### ISSUE TITLE
An error in the logs, but success on solscan

### ISSUE THREAD

**Issue by kartashovio** [okeyzero/jupStaker_SOL#3]
I have started a test script. Delegating 1 jup. I found that many errors are into the logs, but anyway 10-20% transactions success. I see it in solscan. At the same time, there are errors in the script logs, although transaction is success. Tell me, is there any way to fix this?

I understand that Solana does not work well. But then how to work with the script if successful transactions are not tracked?

**Comment by okeyzero** [comment]
There are many reasons for the failure. For example, if it is a 0x1 error, that is, your wallet sol is not enough. After my use, I found that the pledge requires a total balance of 0.01sol in the vote, because there is an account rental fee. You need to take a screenshot of the specific error, and the program will try the error again until it succeeds.

**Comment by kartashovio** [comment]
I understand that the reasons may be different. My data: env:TYPE=1, also have 0.02 SOL+. I tested again just now. You can see on screenshot 2 tries. First: failed. Second: success.
![Screenshot_1](https://github.com/okeyzero/jupStaker_SOL/assets/60577846/0bae3b0d-2b73-4a78-8888-7e672eb0a939)
But check solscan please: there is 2(!) successful transactions.
![Screenshot_2](https://github.com/okeyzero/jupStaker_SOL/assets/60577846/00d4bb99-c982-4607-a208-4c3d651d08af)
I understand, that there is problems with solana stability, but how to work with script in that case?

**Comment by okeyzero** [comment]
Generally speaking, it is indeed an embarrassing problem. The transaction has been issued for a long time, but it has not been chained within 30 seconds, but it is actually on the chain. You can query the transaction results many times, but you will have a lot of time to wait. I hope sol will become better and better. However, I put a fixed number of jup in the tutorial. Once used, it will be prompted in the log, so that I can know the specific error. Of course, I need to exclude this error in the capture error.

**Comment by kartashovio** [comment]
> However, I put a fixed number of jup in the tutorial.

Ok i tested one more case. You can check screenshot below. Case:
- I have 6.2 jup
- .env: AMOUNT=6
Case on screenshot:
1. First try failed in logs, but ok on solscan (successed for 31 seconds+)
2. Then second and later tries were failed. And i am waiting 5-10 minutes: only spam with fails. 

![Screenshot_3](https://github.com/okeyzero/jupStaker_SOL/assets/60577846/0bb34eee-720f-432c-bf5c-b094943b7748)

Decision:
1. It would be ok if script tried only 50 times for example. And then go to the next wallet (keys.txt). 
2. If error `Error: failed to send transaction: Transaction simulation failed: Error pressing Instruction 2: custom program error: 0x1`, try 5-10 times and go next wallet for example

It would be better. Can you code this please?

**Comment by okeyzero** [comment]
I'll continue to refine it when I have time and I'll try to soon
